### ISSUE TITLE
Uses a deprecated API, please fix this

### ISSUE THREAD

**Issue by athul-ain** [AdityaMulgundkar/wallpaper_manager#8]
Note: C:\Users\athul\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.7\android\src\main\java\com\mulgundkar\wallpaper_manager\WallpaperManagerPlugin.java uses or overrides a deprecated API.

**Comment by codingstark-dev** [comment]
> Note: C:\Users\athul\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.7\android\src\main\java\com\mulgundkar\wallpaper_manager\WallpaperManagerPlugin.java uses or overrides a deprecated API.

Ignore this error!

**Comment by codingstark-dev** [comment]
> Note: C:\Users\athul\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.7\android\src\main\java\com\mulgundkar\wallpaper_manager\WallpaperManagerPlugin.java uses or overrides a deprecated API.

add this in your pubspec.yaml

```
dependency_overrides:
   extended_image:
     git:
       url: git://github.com/jonataslaw/extended_image.git
```
